# Generated by Django 5.2.16 on 2026-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, help_text='15-minute pickup hold expiry', null=True),
        ),
    ]
