# Generated by Django 5.2.16 on 2026-07-24 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplaceorder_claim_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old unique constraint (referencing 'customer')
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        # Step 2: Remove old 'customer' FK
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        # Step 3: Add new 'user' FK
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wishlists',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # Step 4: Add new unique constraint (referencing 'user')
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'listing')},
        ),
    ]
