# Generated by Django 5.2.16 on 2026-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_wishlist_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='takedown_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when Admin took down this listing', null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='takedown_reason',
            field=models.CharField(blank=True, help_text='Reason given by Admin when taking down this listing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='listing_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('UNPUBLISHED', 'Unpublished'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
