# Generated by Django 6.0 on 2026-07-11 09:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.CharField(help_text='Name of the person collecting', max_length=255)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='donation_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('donation_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('available_until', models.DateTimeField()),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('visible_to_verified_ngos', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_listings', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_listings', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_listings', to='inventory.inventorybatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_listings', to='products.product')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='donations.donationlisting')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meals_served', models.PositiveIntegerField(default=0)),
                ('food_saved_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('carbon_saved_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('beneficiaries', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('donation_pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='donations.donationpickup')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('request_message', models.TextField(blank=True, null=True)),
                ('approved_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donationlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donationpickup',
            name='donation_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='donations.donationrequest'),
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('service_radius', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Service radius in km', max_digits=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='donations.ngo'),
        ),
        migrations.CreateModel(
            name='NGODocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='ngo_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='donations.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='PickupRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_date', models.DateField()),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_routes', to='donations.ngo')),
                ('pickups', models.ManyToManyField(related_name='routes', to='donations.donationpickup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together={('donation_listing', 'ngo')},
        ),
    ]
