# Generated by Django 6.0 on 2026-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('marketplace', '0004_add_takedown_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuproute',
            name='marketplace_orders',
            field=models.ManyToManyField(blank=True, related_name='pickup_routes', to='marketplace.marketplaceorder'),
        ),
        migrations.AlterField(
            model_name='pickuproute',
            name='pickups',
            field=models.ManyToManyField(blank=True, related_name='routes', to='donations.donationpickup'),
        ),
    ]
