# Generated by Django 6.0 on 2026-07-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_pickuproute_marketplace_orders_and_more'),
        ('marketplace', '0004_add_takedown_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationimpact',
            name='marketplace_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='marketplace.marketplaceorder'),
        ),
        migrations.AlterField(
            model_name='donationimpact',
            name='donation_pickup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='donations.donationpickup'),
        ),
    ]
